name: Run WebdriverIO Tests on BrowserStack

on:
  push:
    branches:
      - main  # or replace with your working branch

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Or match your local version

      - name: Install Dependencies
        run: npm install

      - name: Debug environment (optional)
        run: |
          echo "BROWSERSTACK_USERNAME is set: ${{ secrets.BROWSERSTACK_USERNAME != '' }}"
          echo "Access key length: ${#BROWSERSTACK_ACCESS_KEY}"

      - name: Run WebdriverIO Tests on Pixel
        run: npm run wdio:pixel
    
      - name: Run WebdriverIO Tests on Samsung
        run: npm run wdio:samsung